version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_inditext
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
  app:
    image: prueba_sga
    depends_on:
      - "db"
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_inditext?createDatabaseIfNotExist=true&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: db_inditext
volumes:
  my-db:
