spring:
  application:
    name: POC for Inditex
  mvc:
      pathmatch:
            matching-strategy: ant_path_matcher
  datasource:
    url:  jdbc:mysql://localhost:3306/db_inditext?createDatabaseIfNotExist=true&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&useSSL=false
    #&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:  org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
